const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
exports.run=async({win,docs,openDoc,saveDoc,confirmClose,saveDrafts,draftFile,dialog,core,app,approveWindowClose,persistSettings,settingsFile,loadInitialFile})=>{const results=[],out=process.env.CLARO_AUDIT_DIR||path.join(process.cwd(),'docs/previews/electron'),temp=await fs.mkdtemp(path.join(os.tmpdir(),'claro-electron-'));await fs.mkdir(out,{recursive:true});
 const check=(name,condition)=>{if(!condition)throw Error(name);results.push('PASS '+name);};const execute=source=>win.webContents.executeJavaScript(source);const wait=async source=>{const end=Date.now()+30000;while(Date.now()<end){if(await execute(source))return;await new Promise(r=>setTimeout(r,100));}throw Error('Timeout: '+source);};
 try{win.showInactive();await wait('window.__claroInitialized && window.__claroReady');check('sandbox and isolated context',win.webContents.getLastWebPreferences().sandbox&&win.webContents.getLastWebPreferences().contextIsolation&&!win.webContents.getLastWebPreferences().nodeIntegration);check('renderer has no Node globals',await execute('typeof require === "undefined" && typeof process === "undefined"'));check('quick access and filesystem locations',await execute('document.querySelectorAll(".place").length>=7 && document.querySelector("#places hr")!==null'));
 await wait('Array.from(document.querySelectorAll("#preview img")).some(i=>i.complete&&i.naturalWidth>0)');check('bundled welcome image loads',true);check('editing defaults to rendered document',await execute(`document.body.dataset.mode==='edit'&&getComputedStyle(document.querySelector('#editor-pane')).display==='none'`));const fixture=path.join(temp,'Prueba ñ.md');await fs.writeFile(path.join(temp,'imagen.svg'),'<svg xmlns="http://www.w3.org/2000/svg" width="60" height="40"><rect width="60" height="40" fill="#315fe8"/></svg>');let source=await fs.readFile(path.join(__dirname,'../src/Assets/audit.md'),'utf8');source=source.replace(/!\[[^\]]*\]\([^)]*\)/g,'![Imagen](imagen.svg)');source+='\n<script>window.__injected=true</script>\n[malicioso](javascript:alert(1))\n';source=source.replace(/\r?\n/g,'\r\n');await fs.writeFile(fixture,source);const opened=await openDoc(fixture);await execute(`window.__claroTest.accept(${JSON.stringify(opened)});window.__claroReady=false;`);await wait('window.__claroReady && window.__claroRender.diagrams >= 10');
 check('10 Mermaid diagram families rendered',await execute('window.__claroRender.diagrams>=10'));check('invalid graph has isolated fallback',await execute('window.__claroRender.errors>=1 && document.querySelector(".render-error")!==null'));check('inline and block math',await execute('document.querySelectorAll(".katex").length>=2'));check('code highlighted',await execute('document.querySelector("pre code.hljs")!==null'));check('scrollable tables',await execute('document.querySelector(".table-scroll")!==null'));check('HTML and script cannot execute',await execute('!window.__injected && !document.querySelector("#preview script") && !document.querySelector("#preview a[href^=javascript]")'));await wait('Array.from(document.querySelectorAll("#preview img")).some(i=>i.complete&&i.naturalWidth>0)');check('local Unicode image path works',true);check('headings index exists',await execute('document.querySelectorAll("#outline button").length>0'));
 await execute('window.__claroReady=false;window.__claroTest.setMode("read");window.__claroTest.setTheme("light")');await wait('window.__claroReady');await new Promise(r=>setTimeout(r,400));await fs.writeFile(path.join(out,'light.png'),(await win.webContents.capturePage()).toPNG());await execute('{const p=document.querySelector("#preview-scroll"),m=document.querySelector(".katex-display");p.scrollTop+=m.getBoundingClientRect().top-p.getBoundingClientRect().top-20}');await new Promise(r=>setTimeout(r,300));check('math layout retains generated inline styles',await execute('document.querySelector(".katex [style]")!==null'));await fs.writeFile(path.join(out,'math.png'),(await win.webContents.capturePage()).toPNG());await execute('document.querySelector("#preview-scroll").scrollTop=0');
 await execute('window.__claroTest.setMode("split");window.__claroTest.view().dispatch({changes:{from:0,to:0,insert:"# Editado por la auditoría\\n\\n"}})');await wait('document.querySelector("#save-state").classList.contains("dirty")');check('real editor updates dirty state',true);await execute('window.__claroTest.run("save")');await wait('!document.querySelector("#save-state").classList.contains("dirty")');check('save reaches disk',(await fs.readFile(fixture,'utf8')).startsWith('# Editado por la auditoría'));
 await execute('window.__claroTest.run("bold")');await wait('window.__claroTest.view().state.doc.toString().includes("**")');check('format toolbar edits Markdown',true);await execute('window.__claroTest.run("search")');check('search and replace panel',await execute('document.querySelector(".cm-search")!==null'));await execute('window.__claroTest.setTheme("dark")');await new Promise(r=>setTimeout(r,700));await fs.writeFile(path.join(out,'dark-split.png'),(await win.webContents.capturePage()).toPNG());check('theme dark active',await execute('document.body.dataset.theme==="dark"'));await execute('window.__claroTest.setMode("edit")');check('editing mode hides preview',await execute('getComputedStyle(document.querySelector("#preview-pane")).display==="none"'));await execute('window.__claroTest.setMode("read")');check('reading mode hides editor',await execute('getComputedStyle(document.querySelector("#editor-pane")).display==="none"'));
 const old=docs.get(opened.id);check('CRLF preserved by real editor save',(await fs.readFile(fixture,'utf8')).includes('\r\n'));await fs.writeFile(fixture,'# Cambio externo');await execute('window.__claroTest.view().dispatch({changes:{from:0,to:0,insert:"X"}})');await new Promise(r=>setTimeout(r,100));await require('node:assert/strict').rejects(saveDoc(opened.id),/cambió fuera/);check('external changes cannot be overwritten silently',true);
 await saveDrafts();const recovered=JSON.parse(await fs.readFile(draftFile(),'utf8'));check('dirty draft persisted without overwriting original',recovered.some(d=>d.id===opened.id&&d.content.startsWith('X'))&&(await fs.readFile(fixture,'utf8'))==='# Cambio externo');
 const nativeMessage=dialog.showMessageBox,nativeSave=dialog.showSaveDialog;try{dialog.showMessageBox=async()=>({response:2});check('cancel closing preserves dirty document',!await confirmClose(opened.id)&&docs.has(opened.id));dialog.showSaveDialog=async()=>({canceled:true});check('cancel Save As preserves document',await saveDoc(opened.id,true)===null&&docs.has(opened.id));const copy=path.join(temp,'Copia.md');dialog.showSaveDialog=async()=>({canceled:false,filePath:copy});const copied=await saveDoc(opened.id,true);check('Save As creates separate file',copied.path===copy&&(await fs.readFile(copy,'utf8')).startsWith('X')&&(await fs.readFile(fixture,'utf8'))==='# Cambio externo');dialog.showMessageBox=async()=>({response:1});const scratch=await openDoc(fixture);docs.get(scratch.id).dirty=true;check('discard closing removes only selected tab',await confirmClose(scratch.id)&&!docs.has(scratch.id)&&docs.has(opened.id));}finally{dialog.showMessageBox=nativeMessage;dialog.showSaveDialog=nativeSave;}
 await new Promise(r=>setTimeout(r,650));const textBeforeUndo=await execute('window.__claroTest.view().state.doc.toString()');await execute('window.__claroTest.view().dispatch({changes:{from:0,to:0,insert:"UNDO-TEST"}});window.__claroTest.run("undo")');check('editor undo restores exact text',await execute('window.__claroTest.view().state.doc.toString()')===textBeforeUndo);await execute('window.__claroTest.run("redo")');check('editor redo restores edit',await execute('window.__claroTest.view().state.doc.toString().startsWith("UNDO-TEST")'));
 const firstId=[...docs.keys()].find(id=>id!==opened.id);await execute(`window.__claroTest.activate(${JSON.stringify(firstId)});window.__claroTest.setTheme('dark');window.__claroTest.activate(${JSON.stringify(opened.id)});window.__claroTest.run('undo')`);check('tab and theme changes preserve undo history',await execute('window.__claroTest.view().state.doc.toString()')===textBeforeUndo);
 const pdf=await win.webContents.printToPDF({printBackground:true});check('PDF export generated',pdf.subarray(0,4).toString()==='%PDF');
 await require('./regressions.cjs').run({execute,check,temp,core,openDoc,docs,saveDoc,confirmClose,dialog,draftFile,approveWindowClose,persistSettings,settingsFile,loadInitialFile});
 await require('./visual-audit.cjs').run({execute,check,temp,openDoc,win,wait,out});
 win.setSize(900,650);await execute('window.__claroTest.setMode("split");window.__claroTest.setTheme("light")');await new Promise(r=>setTimeout(r,600));await fs.writeFile(path.join(out,'compact.png'),(await win.webContents.capturePage()).toPNG());check('900px window has no horizontal shell overflow',await execute('document.documentElement.scrollWidth<=innerWidth'));check('offline renderer makes no network connections',await execute('performance.getEntriesByType("resource").every(e=>!/^https?:/.test(e.name))'));check('multiple tabs preserve edits',await execute('window.__claroTest.documents.size>=2'));
 results.push('SUCCESS');await fs.writeFile(path.join(out,'AUDIT-RESULTS.txt'),results.join('\n'));console.log(results.join('\n'));await fs.rm(temp,{recursive:true,force:true});app.exit(0);
 }catch(e){results.push('FAIL '+e.stack);await fs.writeFile(path.join(out,'AUDIT-RESULTS.txt'),results.join('\n'));await fs.writeFile(path.join(out,'failure.png'),(await win.webContents.capturePage()).toPNG());console.error(e);app.exit(1);}finally{await fs.rm(temp,{recursive:true,force:true});}
};
