const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');const core=require('./core.cjs');
test('UTF-8 BOM, UTF-16 LE and exact CRLF preservation',()=>{for(const encoding of ['utf8','utf16le']){const input={encoding,bom:true};const text='# Español\r\nÑ · 日本語\r\n';const bytes=core.encode(text,input),decoded=core.decode(bytes);assert.equal(decoded.content,text);assert.equal(decoded.eol,'CRLF');assert.equal(decoded.encoding,encoding);assert.deepEqual(core.encode(decoded.content,decoded),bytes);}});
test('reject invalid encoding without silently replacing bytes',()=>{assert.throws(()=>core.decode(Buffer.from([254,255,0,65])));assert.throws(()=>core.decode(Buffer.from([195,40])));});
test('F-03 reject truncated UTF-16 and unpaired surrogates',()=>{assert.throws(()=>core.decode(Buffer.from([255,254,65])));assert.throws(()=>core.decode(Buffer.from([255,254,0,216])));assert.equal(core.decode(core.encode('🐈 café',{encoding:'utf16le',bom:true})).content,'🐈 café');});
test('F-03 encoded UTF-16 size must fit limit without modifying original',async()=>{const folder=await fs.mkdtemp(path.join(os.tmpdir(),'lecat-size-'));try{const file=path.join(folder,'nota.md');await fs.writeFile(file,core.encode('Original',{encoding:'utf16le',bom:true}));const d=await core.read(file);await assert.rejects(core.atomicSave(d,'a'.repeat(core.MAX/2)),/codificado mayor/);assert.equal((await core.read(file)).content,'Original');assert.deepEqual(await fs.readdir(folder),['nota.md']);}finally{await fs.rm(folder,{recursive:true,force:true});}});
test('F-03 change during temporary write prevents rename and preserves external bytes',async()=>{const folder=await fs.mkdtemp(path.join(os.tmpdir(),'lecat-conflict-')),write=fs.writeFile;try{const file=path.join(folder,'nota.md');await write(file,'Original');const d=await core.read(file);fs.writeFile=async(target,...args)=>{await write(target,...args);if(String(target).includes('.claro-'))await write(file,'Cambio externo durante guardado');};await assert.rejects(core.atomicSave(d,'Editado'),/durante el guardado/);assert.equal(await fs.readFile(file,'utf8'),'Cambio externo durante guardado');assert.deepEqual(await fs.readdir(folder),['nota.md']);}finally{fs.writeFile=write;await fs.rm(folder,{recursive:true,force:true});}});
test('atomic save and external conflict protection',async()=>{const folder=await fs.mkdtemp(path.join(os.tmpdir(),'claro-test-'));try{const file=path.join(folder,'nota.md');await fs.writeFile(file,'# Original\r\n');const doc=await core.read(file);const saved=await core.atomicSave(doc,'# Editado\r\n');assert.equal((await core.read(file)).content,'# Editado\r\n');await fs.writeFile(file,'# Otro programa');await assert.rejects(core.atomicSave(saved,'# Sobrescribir'),/cambió fuera/);assert.equal(await fs.readFile(file,'utf8'),'# Otro programa');assert.equal((await fs.readdir(folder)).length,1);}finally{await fs.rm(folder,{recursive:true,force:true});}});
test('new target conflict and file deletion are detected',async()=>{const folder=await fs.mkdtemp(path.join(os.tmpdir(),'claro-test-'));try{const file=path.join(folder,'nota.md');await fs.writeFile(file,'Hola');await assert.rejects(core.atomicSave({path:file,hash:null},'Otro'),/cambió fuera/);const doc=await core.read(file);await fs.unlink(file);await assert.rejects(core.atomicSave(doc,'Otro'),/cambió fuera/);}finally{await fs.rm(folder,{recursive:true,force:true});}});
test('only Markdown and directories in explorer',async()=>{const folder=await fs.mkdtemp(path.join(os.tmpdir(),'claro-test-'));try{await fs.writeFile(path.join(folder,'nota.MD'),'Hola');await fs.writeFile(path.join(folder,'secreto.txt'),'No');await fs.mkdir(path.join(folder,'carpeta'));assert.deepEqual((await core.list(folder)).map(e=>e.name),['carpeta','nota.MD']);await assert.rejects(core.read(path.join(folder,'secreto.txt')),/Markdown/);}finally{await fs.rm(folder,{recursive:true,force:true});}});
