const {app,BrowserWindow,ipcMain,dialog,Menu,shell,protocol,net,nativeTheme}=require('electron');
const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto'),{pathToFileURL}=require('node:url'),{execFile}=require('node:child_process');
const core=require('./core.cjs');
protocol.registerSchemesAsPrivileged([{scheme:'claro-media',privileges:{standard:true,secure:true,supportFetchAPI:true}}]);
const auditing=process.argv.includes('--audit');let win,settings={},closing=false,closeInProgress=false;const docs=new Map(),mediaRoots=new Map(),folders=new Set();let draftTimer,draftQueue=Promise.resolve();
if(!auditing){const userProfile=path.join(app.getPath('appData'),'ClaroMD');require('node:fs').mkdirSync(userProfile,{recursive:true});app.setPath('userData',userProfile);}
if(auditing){const auditProfile=path.join(require('node:os').tmpdir(),'claro-audit-profile-'+crypto.randomUUID());require('node:fs').mkdirSync(auditProfile);app.setPath('userData',auditProfile);}
if(!auditing&&!app.requestSingleInstanceLock())app.exit(0);
app.setAppUserModelId('com.lecat.markdown');
app.on('second-instance',async(_event,argv)=>{if(!win)return;if(win.isMinimized())win.restore();win.show();win.focus();const file=argv.find(a=>/\.(md|markdown)$/i.test(a)&&path.isAbsolute(a));if(file)try{command({openDoc:await openDoc(file)});}catch(e){dialog.showMessageBox(win,{type:'error',message:e.message});}});
const settingsFile=()=>path.join(app.getPath('userData'),'settings.json');const draftFile=()=>path.join(app.getPath('userData'),'drafts.json');
const saveJobs=new Map();
const mediaCache=new Map();
function releaseMedia(id){const cache=mediaCache.get(id);if(cache)for(const token of cache.values())mediaRoots.delete(token);mediaCache.delete(id);}
function publicDoc(d){return {id:d.id,path:d.path,name:d.name,content:d.content,dirty:d.dirty,encoding:d.encoding,eol:d.eol};}
function addDoc(d){d.id=crypto.randomUUID();d.dirty=!!d.dirty;d.savedContent=d.savedContent??d.content;docs.set(d.id,d);if(d.path)folders.add(path.dirname(d.path));return publicDoc(d);}
async function openDoc(file){const existing=[...docs.values()].find(d=>d.path&&path.resolve(d.path).toLowerCase()===path.resolve(file).toLowerCase());return existing?publicDoc(existing):addDoc(await core.read(file));}
async function saveDrafts(){const snapshot=JSON.stringify([...docs.values()].filter(d=>d.dirty));draftQueue=draftQueue.catch(()=>{}).then(async()=>{await fs.mkdir(app.getPath('userData'),{recursive:true});const temp=draftFile()+'.tmp';await fs.writeFile(temp,snapshot);await fs.rename(temp,draftFile());});await draftQueue;}
async function updateDrafts(){clearTimeout(draftTimer);draftTimer=setTimeout(()=>saveDrafts().catch(()=>{}),350);}
async function saveDoc(id,as=false){const previous=saveJobs.get(id)||Promise.resolve();const job=previous.catch(()=>{}).then(()=>performSaveDoc(id,as));saveJobs.set(id,job);try{return await job;}finally{if(saveJobs.get(id)===job)saveJobs.delete(id);}}
async function performSaveDoc(id,as=false){const doc=docs.get(id);if(!doc)throw Error('Documento no abierto.');let target=doc.path;
 if(as||!target){const result=await dialog.showSaveDialog(win,{title:'Guardar Markdown',defaultPath:target||path.join(app.getPath('documents'),doc.name),filters:[{name:'Markdown',extensions:['md','markdown']}]});if(result.canceled)return null;target=result.filePath;if(!/\.(md|markdown)$/i.test(target))target+='.md';}
 let output={...doc,path:target};
 if(target!==doc.path){if([...docs.values()].some(d=>d.id!==id&&d.path?.toLowerCase()===target.toLowerCase()))throw Error('Ese archivo ya está abierto en otra pestaña.');output={...output,hash:null,encoding:'utf8',bom:false};}
 const snapshot=doc.content;const saved=await core.atomicSave(output,snapshot,{allowOverwrite:target!==doc.path||!doc.path});const currentContent=doc.content;Object.assign(doc,saved,{content:currentContent,dirty:currentContent!==snapshot,savedContent:snapshot,name:path.basename(target)});folders.add(path.dirname(target));await saveDrafts();return publicDoc(doc);
}
async function confirmClose(id,remove=true){if(saveJobs.has(id))await saveJobs.get(id);const d=docs.get(id);if(!d)return true;if(d.dirty){const choice=await dialog.showMessageBox(win,{type:'warning',title:'Cambios sin guardar',message:`¿Guardar los cambios de ${d.name}?`,buttons:['Guardar','Descartar','Cancelar'],defaultId:0,cancelId:2,noLink:true});if(choice.response===2)return false;if(choice.response===0){const saved=await saveDoc(id);if(!saved||d.dirty)return false;}}if(remove){docs.delete(id);releaseMedia(id);await saveDrafts();}return true;}
function command(cmd){win.webContents.send('command',cmd);}
function setMenu(){const item=(label,accelerator,cmd)=>({label,accelerator,click:()=>command(cmd)});Menu.setApplicationMenu(Menu.buildFromTemplate([
 {label:'Archivo',submenu:[item('Nuevo','Ctrl+N','new'),item('Abrir documento…','Ctrl+O','open'),item('Abrir carpeta…','Ctrl+Shift+O','folder'),{type:'separator'},item('Guardar','Ctrl+S','save'),item('Guardar como…','Ctrl+Shift+S','saveAs'),item('Exportar PDF…','Ctrl+Alt+P','pdf'),{type:'separator'},item('Cerrar pestaña','Ctrl+W','close'),{label:'Salir',click:()=>win.close()}]},
 {label:'Editar',submenu:[item('Deshacer','Ctrl+Z','undo'),item('Rehacer','Ctrl+Y','redo'),{type:'separator'},{role:'cut',label:'Cortar'},{role:'copy',label:'Copiar'},{role:'paste',label:'Pegar'},{role:'selectAll',label:'Seleccionar todo'},item('Buscar / reemplazar','Ctrl+F','search'),item('Negrita','Ctrl+B','bold'),item('Cursiva','Ctrl+I','italic')]},
 {label:'Vista',submenu:[item('Lectura','Ctrl+1','read'),item('Edición','Ctrl+2','edit'),item('Edición y vista previa','Ctrl+3','split'),item('Modo enfoque','Ctrl+Shift+F','focus'),item('Cambiar tema','Ctrl+Shift+T','theme'),{role:'togglefullscreen',label:'Pantalla completa'},item('Acercar','Ctrl+=','zoomIn'),item('Alejar','Ctrl+-','zoomOut'),item('Restablecer zoom','Ctrl+0','zoomReset')]},
 {label:'Ayuda',submenu:[{label:'Acerca de Lecat - Markdown',click:()=>dialog.showMessageBox(win,{title:'Lecat - Markdown',message:'Lecat - Markdown · Electron',detail:'Editor y lector Markdown sin conexión. Chromium incluido. Ctrl+1 Lectura · Ctrl+2 Edición · Ctrl+3 Vista dividida. Guardado explícito con Ctrl+S y recuperación de borradores.'})}]}]));}
async function places(){const names=[['desktop','Escritorio'],['downloads','Descargas'],['documents','Documentos'],['pictures','Imágenes'],['music','Música'],['videos','Vídeos']];const quick=names.map(([id,name])=>({name,path:app.getPath(id),directory:true}));let drives=[],extra=[];
 if(process.platform==='win32'){
 const script="[Console]::OutputEncoding=[Text.UTF8Encoding]::new(); $q=(New-Object -ComObject Shell.Application).NameSpace('shell:::{679f85cb-0220-4080-b29b-5540cc05aab6}').Items() | Where-Object {$_.IsFolder -and [IO.Directory]::Exists($_.Path)} | ForEach-Object { @{name=$_.Name;path=$_.Path;directory=$true} }; $d=Get-CimInstance Win32_LogicalDisk | ForEach-Object { @{name=($_.DeviceID+' '+$_.VolumeName).Trim();path=($_.DeviceID+'\\');directory=$true} }; @{quick=@($q);drives=@($d)} | ConvertTo-Json -Depth 4 -Compress";
 try{const value=await new Promise((resolve,reject)=>execFile('powershell.exe',['-NoProfile','-NonInteractive','-Command',script],{windowsHide:true,timeout:6000,encoding:'utf8'},(e,out)=>e?reject(e):resolve(JSON.parse(out))));drives=value.drives;extra=value.quick.filter(q=>!quick.some(k=>k.path.toLowerCase()===q.path.toLowerCase()));}catch{for(const letter of 'ABCDEFGHIJKLMNOPQRSTUVWXYZ')try{await fs.access(letter+':\\');drives.push({name:letter+':',path:letter+':\\',directory:true});}catch{}}
 }else drives=[{name:'Sistema',path:'/',directory:true}];
 for(const p of [...quick,...extra,...drives])folders.add(p.path);return {quick,extra,drives};
}
function register(name,handler){ipcMain.handle('claro:'+name,async(e,...args)=>{if(e.sender!==win.webContents||e.senderFrame!==win.webContents.mainFrame||e.senderFrame.url!==pathToFileURL(path.join(__dirname,'ui/index.html')).href)throw Error('Origen no autorizado.');try{return {ok:true,value:await handler(...args)};}catch(error){return {ok:false,error:error.message};}});}
app.whenReady().then(async()=>{
 try{settings=JSON.parse(await fs.readFile(settingsFile(),'utf8'));}catch{}
 nativeTheme.themeSource=settings.theme==='dark'?'dark':'light';
 protocol.handle('claro-media',async request=>{try{const u=new URL(request.url),file=mediaRoots.get(u.hostname);if(!file||decodeURIComponent(u.pathname)!=='/'+path.basename(file))return new Response('',{status:403});if((await fs.stat(file)).size>core.MAX)return new Response('',{status:413});return net.fetch(pathToFileURL(file).href);}catch{return new Response('',{status:404});}});
 win=new BrowserWindow({width:1320,height:860,minWidth:820,minHeight:560,show:false,backgroundColor:'#f7f8fa',title:'Lecat - Markdown',icon:path.join(__dirname,'../branding/Lecat.ico'),autoHideMenuBar:false,webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true,spellcheck:false}});
 win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',e=>e.preventDefault());win.webContents.session.setPermissionRequestHandler((_wc,_p,cb)=>cb(false));
 win.on('close',e=>{if(closing||auditing)return;e.preventDefault();if(closeInProgress)return;closeInProgress=true;(async()=>{for(const id of [...docs.keys()])if(!(await confirmClose(id,false)))return;docs.clear();clearTimeout(draftTimer);await saveDrafts();closing=true;win.close();})().catch(error=>dialog.showMessageBox(win,{type:'error',message:error.message})).finally(()=>{closeInProgress=false;});});
 register('bootstrap',async()=>{const locations=await places();let recovered=[];if(!auditing)try{recovered=JSON.parse(await fs.readFile(draftFile(),'utf8')).map(d=>addDoc({...d,dirty:true}));}catch{}
 const initial=process.argv.find(a=>/\.(md|markdown)$/i.test(a)&&path.isAbsolute(a));if(initial)try{recovered.push(await openDoc(initial));}catch{}
 if(!recovered.length){const example=await core.read(path.join(__dirname,'../examples/Bienvenido.md'));recovered.push(addDoc({...example,path:null,hash:null,assetBase:path.dirname(example.path)}));}return {places:locations,settings,docs:recovered,auditing};});
 register('list',async folder=>{if(typeof folder!=='string'||!path.isAbsolute(folder))throw Error('Ruta no válida.');const result=await core.list(folder);folders.add(folder);for(const e of result)if(e.directory)folders.add(e.path);return result;});
 register('open',async file=>{if(typeof file!=='string'||!path.isAbsolute(file))throw Error('Ruta no válida.');return openDoc(file);});
 register('new',()=>addDoc({name:'Sin título.md',content:'',encoding:'utf8',bom:false,eol:'LF',hash:null,path:null}));
 register('update',async(id,content)=>{const d=docs.get(id);if(!d||typeof content!=='string'||Buffer.byteLength(content)>core.MAX)throw Error('Documento no válido.');d.content=d.eol==='CRLF'?content.replace(/\r?\n/g,'\r\n'):content;d.dirty=d.content!==d.savedContent;await updateDrafts();return d.dirty;});
 register('save',id=>saveDoc(id));register('saveAs',id=>saveDoc(id,true));register('close',id=>confirmClose(id));
 register('pickFile',async()=>{const r=await dialog.showOpenDialog(win,{properties:['openFile'],filters:[{name:'Markdown',extensions:['md','markdown']}]});return r.canceled?null:openDoc(r.filePaths[0]);});
 register('pickFolder',async()=>{const r=await dialog.showOpenDialog(win,{properties:['openDirectory']});return r.canceled?null:r.filePaths[0];});
 register('settings',async value=>{settings={theme:value.theme==='dark'?'dark':'light',mode:['read','edit','split'].includes(value.mode)?value.mode:'split',zoom:Math.min(1.5,Math.max(.8,Number(value.zoom)||1))};nativeTheme.themeSource=settings.theme;if(!auditing){await fs.mkdir(app.getPath('userData'),{recursive:true});await fs.writeFile(settingsFile(),JSON.stringify(settings));}return settings;});
 register('link',async(id,href)=>{if(typeof href!=='string')throw Error('Enlace no válido.');if(/^https?:\/\//i.test(href)){await shell.openExternal(new URL(href).href);return null;}const d=docs.get(id);if(!d?.path||/^[a-z]+:/i.test(href))throw Error('Enlace no permitido.');return openDoc(path.resolve(path.dirname(d.path),decodeURIComponent(href.split('#')[0])));});
 register('media',async(id,href)=>{const d=docs.get(id),base=d?.path?path.dirname(d.path):d?.assetBase;if(!base||typeof href!=='string'||/^[a-z]+:/i.test(href))throw Error('Imagen no permitida.');const file=await fs.realpath(path.resolve(base,decodeURIComponent(href)));if(!/\.(png|jpe?g|gif|webp|svg|bmp|avif)$/i.test(file)||(await fs.stat(file)).size>core.MAX)throw Error('Imagen no válida.');let cache=mediaCache.get(id);if(!cache){cache=new Map();mediaCache.set(id,cache);}let token=cache.get(file);if(!token){token=crypto.randomUUID();cache.set(file,token);mediaRoots.set(token,file);}return 'claro-media://'+token+'/'+encodeURIComponent(path.basename(file));});
 register('exportSvg',async svg=>{if(typeof svg!=='string'||svg.length>2000000||!svg.startsWith('<svg'))throw Error('Gráfico no válido.');const r=await dialog.showSaveDialog(win,{defaultPath:'grafico.svg',filters:[{name:'SVG',extensions:['svg']}]});if(!r.canceled)await fs.writeFile(r.filePath,svg);return !r.canceled;});
 register('exportPdf',async()=>{const r=await dialog.showSaveDialog(win,{defaultPath:'documento.pdf',filters:[{name:'PDF',extensions:['pdf']}]});if(r.canceled)return false;await fs.writeFile(r.filePath,await win.webContents.printToPDF({printBackground:true,preferCSSPageSize:true}));return true;});
 register('window',action=>{if(action==='minimize')win.minimize();else if(action==='maximize')win.isMaximized()?win.unmaximize():win.maximize();else if(action==='close')win.close();});
 register('audit',async()=>{if(!auditing)throw Error('Auditoría desactivada.');return true;});
 if(auditing)win.webContents.session.webRequest.onBeforeRequest({urls:['http://*/*','https://*/*']},(_details,cb)=>cb({cancel:true}));
 setMenu();await win.loadFile(path.join(__dirname,'ui/index.html'));if(!auditing)win.show();else await require('./audit.cjs').run({win,docs,openDoc,saveDoc,confirmClose,saveDrafts,draftFile,dialog,core,app});
}).catch(e=>{console.error(e);app.exit(1);});
app.on('window-all-closed',()=>app.quit());
