const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
exports.run=async({execute,check,temp,core,openDoc,docs,saveDoc,confirmClose,dialog})=>{
 const aPath=path.join(temp,'Race A.md'),bPath=path.join(temp,'Race B.md');await fs.writeFile(aPath,'# A original');await fs.writeFile(bPath,'# B original');const a=await openDoc(aPath),b=await openDoc(bPath);
 await execute(`window.__claroTest.accept(${JSON.stringify(b)});window.__claroTest.accept(${JSON.stringify(a)});window.__claroTest.view().dispatch({changes:{from:0,to:window.__claroTest.view().state.doc.length,insert:'# A editado'}});window.__saveRace=window.__claroTest.run('save');window.__claroTest.activate(${JSON.stringify(b.id)});`);await execute('window.__saveRace');
 check('F-01 saving while switching tabs writes intended file',(await fs.readFile(aPath,'utf8'))==='# A editado'&&(await fs.readFile(bPath,'utf8'))==='# B original');check('F-01 save response cannot replace active tab identity',await execute(`window.__claroTest.doc().id===${JSON.stringify(b.id)} && window.__claroTest.view().state.doc.toString()==='# B original'`));
 const originalSave=core.atomicSave,originalMessage=dialog.showMessageBox;let release,entered;const started=new Promise(r=>entered=r),gate=new Promise(r=>release=r);try{
 core.atomicSave=async(...args)=>{entered();await gate;return originalSave(...args);};dialog.showMessageBox=async()=>({response:0});const d=docs.get(a.id);d.content='# Versión al guardar';d.dirty=true;const close=confirmClose(a.id);await started;d.content='# Cambios mientras guarda';d.dirty=true;release();check('F-02 closing after save retains newer edits',!await close&&docs.has(a.id)&&d.dirty&&d.content==='# Cambios mientras guarda');check('F-02 pending close saved only approved snapshot',(await fs.readFile(aPath,'utf8'))==='# Versión al guardar');
 }finally{release?.();core.atomicSave=originalSave;dialog.showMessageBox=originalMessage;}
 let releaseQueue,enteredQueue;const startedQueue=new Promise(r=>enteredQueue=r),queueGate=new Promise(r=>releaseQueue=r);let first=true;try{core.atomicSave=async(...args)=>{if(first){first=false;enteredQueue();await queueGate;}return originalSave(...args);};const d=docs.get(a.id);d.content='# Guardado uno';d.dirty=true;const one=saveDoc(a.id);await startedQueue;d.content='# Guardado dos';d.dirty=true;const two=saveDoc(a.id);releaseQueue();await Promise.all([one,two]);check('F-02 concurrent saves serialize latest content',(await fs.readFile(aPath,'utf8'))==='# Guardado dos'&&!d.dirty);}finally{releaseQueue?.();core.atomicSave=originalSave;}
};
