const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
exports.run=async({execute,check,temp,core,openDoc,docs,saveDoc,confirmClose,dialog})=>{
 const aPath=path.join(temp,'Race A.md'),bPath=path.join(temp,'Race B.md');await fs.writeFile(aPath,'# A original');await fs.writeFile(bPath,'# B original');const a=await openDoc(aPath),b=await openDoc(bPath);
 await execute(`window.__claroTest.accept(${JSON.stringify(b)});window.__claroTest.accept(${JSON.stringify(a)});window.__claroTest.view().dispatch({changes:{from:0,to:window.__claroTest.view().state.doc.length,insert:'# A editado'}});window.__saveRace=window.__claroTest.run('save');window.__claroTest.activate(${JSON.stringify(b.id)});`);await execute('window.__saveRace');
 check('F-01 saving while switching tabs writes intended file',(await fs.readFile(aPath,'utf8'))==='# A editado'&&(await fs.readFile(bPath,'utf8'))==='# B original');check('F-01 save response cannot replace active tab identity',await execute(`window.__claroTest.doc().id===${JSON.stringify(b.id)} && window.__claroTest.view().state.doc.toString()==='# B original'`));
 const originalSave=core.atomicSave,originalMessage=dialog.showMessageBox;let release,entered;const started=new Promise(r=>entered=r),gate=new Promise(r=>release=r);try{
 core.atomicSave=async(...args)=>{entered();await gate;return originalSave(...args);};dialog.showMessageBox=async()=>({response:0});const d=docs.get(a.id);d.content='# Versión al guardar';d.dirty=true;const close=confirmClose(a.id);await started;d.content='# Cambios mientras guarda';d.dirty=true;release();check('F-02 closing after save retains newer edits',!await close&&docs.has(a.id)&&d.dirty&&d.content==='# Cambios mientras guarda');check('F-02 pending close saved only approved snapshot',(await fs.readFile(aPath,'utf8'))==='# Versión al guardar');
 }finally{release?.();core.atomicSave=originalSave;dialog.showMessageBox=originalMessage;}
 let releaseQueue,enteredQueue;const startedQueue=new Promise(r=>enteredQueue=r),queueGate=new Promise(r=>releaseQueue=r);let first=true;try{core.atomicSave=async(...args)=>{if(first){first=false;enteredQueue();await queueGate;}return originalSave(...args);};const d=docs.get(a.id);d.content='# Guardado uno';d.dirty=true;const one=saveDoc(a.id);await startedQueue;d.content='# Guardado dos';d.dirty=true;const two=saveDoc(a.id);releaseQueue();await Promise.all([one,two]);check('F-02 concurrent saves serialize latest content',(await fs.readFile(aPath,'utf8'))==='# Guardado dos'&&!d.dirty);}finally{releaseQueue?.();core.atomicSave=originalSave;}
 const earlier='# Preview anterior\n\n```mermaid\nflowchart LR\nA[Inicio]-->B[Final]\n```',latest='# Preview actual\n\n$E=mc^2$';await execute(`{const t=window.__claroTest,v=t.view();v.dispatch({changes:{from:0,to:v.state.doc.length,insert:${JSON.stringify(earlier)}}});window.__oldPreview=t.render();v.dispatch({changes:{from:0,to:v.state.doc.length,insert:${JSON.stringify(latest)}}});window.__latestPreview=t.render();}`);await execute('window.__latestPreview');check('F-04 render promise waits latest preview generation',await execute(`document.querySelector('#preview h1').textContent==='Preview actual' && document.querySelector('#preview .katex')!==null`));
 const originalDialog=dialog.showSaveDialog,pdfPath=path.join(temp,'Ultimo.pdf');try{dialog.showSaveDialog=async()=>({canceled:false,filePath:pdfPath});await execute('window.__claroTest.run("pdf")');check('F-04 PDF export completes after pending rendering',(await fs.readFile(pdfPath)).subarray(0,4).toString()==='%PDF'&&await execute(`document.querySelector('#preview h1').textContent==='Preview actual'`));}finally{dialog.showSaveDialog=originalDialog;}
 const mediaDocPath=path.join(temp,'Media.md');await fs.writeFile(mediaDocPath,'# Imagen');const mediaDoc=await openDoc(mediaDocPath);const urls=await execute(`Promise.all(Array.from({length:50},()=>window.__claroTest.api('media',${JSON.stringify(mediaDoc.id)},'imagen.svg')))`);check('F-05 repeated previews reuse image capability',new Set(urls).size===1);const net=require('electron').net;check('F-05 image capability loads selected file',(await net.fetch(urls[0])).status===200);const other=urls[0].replace('imagen.svg','otra.svg');check('F-05 capability cannot read sibling file',(await net.fetch(other)).status===403);await confirmClose(mediaDoc.id);check('F-05 closing document revokes image capability',(await net.fetch(urls[0])).status===403);
 const folderA=path.join(temp,'Carpeta A'),folderB=path.join(temp,'Carpeta B');await fs.mkdir(folderA);await fs.mkdir(folderB);await fs.writeFile(path.join(folderA,'a.md'),'A');await fs.writeFile(path.join(folderB,'b.md'),'B');let releaseFolder,enteredFolder;const folderGate=new Promise(r=>releaseFolder=r),folderStarted=new Promise(r=>enteredFolder=r),originalList=core.list;try{core.list=async folder=>{if(folder===folderA){enteredFolder();await folderGate;}return originalList(folder);};await execute(`window.__folderRace=window.__claroTest.loadFolder(${JSON.stringify(folderA)});true;`);await folderStarted;await execute(`window.__claroTest.loadFolder(${JSON.stringify(folderB)})`);releaseFolder();await execute('window.__folderRace');check('F-06 late explorer response cannot revert navigation',await execute(`document.querySelector('#path').value===${JSON.stringify(folderB)} && document.querySelector('#files').textContent.includes('b.md')`));}finally{releaseFolder?.();core.list=originalList;}
 const anchorText='# Inicio\n\n[Saltar](#editor)\n\n'+('Párrafo de prueba.\n\n'.repeat(50))+'## Editor\n\nDestino de la navegación.';await execute(`{const v=window.__claroTest.view();v.dispatch({changes:{from:0,to:v.state.doc.length,insert:${JSON.stringify(anchorText)}}});}`);await execute('window.__claroTest.render()');await execute(`document.querySelector('#preview-scroll').scrollTop=0;document.querySelector('#preview a').click();`);await new Promise(r=>setTimeout(r,600));check('F-06 anchors scroll only scoped reading panel',await execute(`document.querySelector('#preview-scroll').scrollTop>100 && document.querySelector('.appbar').getBoundingClientRect().top===0`));
 const targetPath=path.join(temp,'Destino.md');await fs.writeFile(targetPath,anchorText);await execute(`window.__claroTest.api('link',${JSON.stringify(b.id)},'Destino.md#editor').then(window.__claroTest.accept)`);await execute('window.__claroTest.render()');await new Promise(r=>setTimeout(r,600));check('F-06 relative document links retain heading anchor',await execute(`window.__claroTest.doc().path===${JSON.stringify(targetPath)} && document.querySelector('#preview-scroll').scrollTop>100`));
};
