import {createVisual} from './visual.js';
import {frontMatterPlugin} from './frontmatter.js';
import {EditorView,keymap} from '@codemirror/view';
import {EditorState,Compartment} from '@codemirror/state';
import {basicSetup} from 'codemirror';import {undo,redo} from '@codemirror/commands';
import {markdown} from '@codemirror/lang-markdown';
import {openSearchPanel} from '@codemirror/search';
import {oneDark} from '@codemirror/theme-one-dark';
import MarkdownIt from 'markdown-it';import tasks from 'markdown-it-task-lists';import DOMPurify from 'dompurify';import katex from 'katex';import mermaid from 'mermaid';import hljs from 'highlight.js';
import 'katex/dist/katex.min.css';import 'highlight.js/styles/github.css';
import {createIcons,FilePlus,FileText,Save,SunMoon,FolderOpen,Folder,ArrowUp,RefreshCw,Search,BookOpen,Pencil,Columns2,ListTree,Maximize,Minus,Plus,Heading2,Bold,Italic,Link,Image,List,ListChecks,Quote,Code,Table,Workflow,X,HardDrive,Download,Monitor,Music,Video,Images,ChevronRight} from 'lucide';
const iconSet={FilePlus,FileText,Save,SunMoon,FolderOpen,Folder,ArrowUp,RefreshCw,Search,BookOpen,Pencil,Columns2,ListTree,Maximize,Minus,Plus,Heading2,Bold,Italic,Link,Image,List,ListChecks,Quote,Code,Table,Workflow,X,HardDrive,Download,Monitor,Music,Video,Images,ChevronRight};
const $=s=>document.querySelector(s);const icons=()=>createIcons({icons:iconSet});
const documents=new Map();let active=null,view,currentFolder='',entries=[],theme='light',themePreference='system',mode='edit',zoom=1,muting=false,renderTimer,generation=0,rendering=false,pending=false,initializing=true;
let visual=null,visualOrigin=false;
let renderPromise=null,previewGeneration=-1,folderGeneration=0;
const themeSlot=new Compartment();const api=async(name,...args)=>{const result=await window.claro[name](...args);if(!result.ok)throw Error(result.error);return result.value;};
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,6000);}
function icon(name){const i=document.createElement('i');i.dataset.lucide=name;return i;}
function textButton(label,iconName,fn){const b=document.createElement('button');if(iconName)b.append(icon(iconName));const s=document.createElement('span');s.textContent=label;b.append(s);b.addEventListener('click',()=>Promise.resolve(fn()).catch(e=>toast(e.message)));return b;}
function doc(){return documents.get(active);}
async function sync(id=active){const target=documents.get(id);if(target)await api('update',id,id===active?view.state.doc.toString():target.state?.doc.toString()??target.content);}
function mergeDocument(saved){const target=documents.get(saved.id);if(!target)return;const content=saved.id===active?view.state.doc.toString():target.state?.doc.toString()??target.content;const normalized=text=>saved.eol==='CRLF'?text.replace(/\r?\n/g,'\r\n'):text;Object.assign(target,saved,{content,dirty:saved.dirty||normalized(content)!==normalized(saved.content)});}
function applyVisual(source){const old=view.state.doc.toString();if(old===source)return;let from=0;while(from<old.length&&from<source.length&&old[from]===source[from])from++;let a=old.length,b=source.length;while(a>from&&b>from&&old[a-1]===source[b-1]){a--;b--;}visualOrigin=true;try{view.dispatch({changes:{from,to:a,insert:source.slice(from,b)}});}finally{visualOrigin=false;}}
function askVisual(title,value,multiline){return new Promise(resolve=>{const id=active,before=view.state.doc.toString(),dialog=$('#edit-dialog'),field=$('#edit-value');$('#edit-title').textContent=title;field.value=value;field.rows=multiline?9:2;dialog.onclose=()=>{dialog.onclose=null;if(dialog.returnValue==='apply'&&(id!==active||view.state.doc.toString()!==before)){toast('El documento cambió mientras el diálogo estaba abierto. Volvé a abrirlo.');resolve(null);}else resolve(dialog.returnValue==='apply'?field.value:null);};dialog.returnValue='cancel';dialog.showModal();field.focus();field.select();});}
function stats(){const d=doc(),text=view?.state.doc.toString()||'',pos=view?.state.selection.main.head||0,line=view?.state.doc.lineAt(pos);$('#stats').textContent=`${text.trim()?text.trim().split(/\s+/).length:0} palabras · ${text.length} caracteres`;$('#cursor').textContent=mode==='edit'?'Edición visual':`Línea ${line?.number||1}, columna ${line?pos-line.from+1:1}`;$('#encoding').textContent=`${d?.encoding==='utf16le'?'UTF-16 LE':'UTF-8'} · ${d?.eol||'LF'}`;}
function chrome(){const d=doc();$('#doc-title').textContent=d?.name||'Sin título';$('#doc-path').textContent=d?.path||'Nuevo documento · elegí dónde guardarlo';$('#save-state').textContent=d?.dirty?'Sin guardar':'Guardado';$('#save-state').classList.toggle('dirty',!!d?.dirty);document.title=(d?.dirty?'● ':'')+(d?.name||'Lecat - Markdown')+' · Lecat - Markdown';const tabs=$('#tabs');tabs.replaceChildren();for(const d of documents.values()){const tab=document.createElement('div');tab.className='tab'+(d.id===active?' active':'');tab.setAttribute('role','tab');tab.setAttribute('aria-selected',String(d.id===active));tab.title=d.path||d.name;tab.append(textButton((d.dirty?'● ':'')+d.name,'file-text',()=>activate(d.id)));const close=textButton('','x',()=>closeDoc(d.id));close.className='close-tab';close.setAttribute('aria-label','Cerrar '+d.name);tab.append(close);tabs.append(tab);}icons();stats();}
function activate(id){if(!documents.has(id))return;if(doc()){doc().state=view.state;doc().content=view.state.doc.toString();}active=id;const d=doc();muting=true;view.setState(d.state||makeState(d.content));muting=false;visual?.load(view.state.doc.toString(),true);chrome();schedule();}
function accept(d){if(!d)return;if(!documents.has(d.id))documents.set(d.id,d);else Object.assign(documents.get(d.id),d);if(d.anchor)documents.get(d.id).pendingAnchor=d.anchor;activate(d.id);if(d.path)loadFolder(d.path.replace(/[\\/][^\\/]*$/,'')).catch(()=>{});}
function makeState(content){return EditorState.create({doc:content,extensions:[basicSetup,markdown(),EditorState.phrases.of({Find:"Buscar",Replace:"Reemplazar",next:"Siguiente",previous:"Anterior",all:"Todos","match case":"Mayúsculas",regexp:"Exp. regular","by word":"Palabra",replace:"Reemplazar","replace all":"Reemplazar todos",close:"Cerrar","Go to line":"Ir a línea",go:"Ir"}),EditorView.lineWrapping,themeSlot.of(theme==='dark'?oneDark:[]),EditorView.updateListener.of(update=>{stats();if(update.docChanged&&!muting){const d=doc();if(d){d.content=update.state.doc.toString();d.dirty=true;const updatedContent=d.content;api('update',d.id,updatedContent).then(dirty=>{if(d.content===updatedContent){d.dirty=dirty;chrome();}}).catch(e=>toast(e.message));chrome();if(!visualOrigin&&mode==='edit')visual?.load(update.state.doc.toString());schedule();}}}),keymap.of([{key:'Mod-s',run:()=>{run('save');return true;}},{key:'Mod-b',run:()=>{format('bold');return true;}},{key:'Mod-i',run:()=>{format('italic');return true;}}])]});}
function format(kind){if(mode==='read')setMode('edit');if(mode==='edit'){visual?.format(kind).catch(e=>toast(e.message));return;}const selection=view.state.selection.main,chosen=view.state.sliceDoc(selection.from,selection.to);const forms={bold:['**','**','texto'],italic:['_','_','texto'],heading:['## ','','Título'],link:['[','](https://ejemplo.com)','enlace'],image:['![','](imagen.png)','Descripción'],list:['- ','','Elemento'],task:['- [ ] ','','Tarea'],quote:['> ','','Cita'],code:['```javascript\n','\n```','console.log("Hola");'],table:['\n| Columna | Valor |\n| --- | --- |\n| ',' | Dato |\n','Fila'],diagram:['\n```mermaid\n','\n```\n','flowchart LR\n  A[Idea] --> B[Resultado]']};const [before,after,fallback]=forms[kind];const content=chosen||fallback;view.dispatch({changes:{from:selection.from,to:selection.to,insert:before+content+after},selection:{anchor:selection.from+before.length,head:selection.from+before.length+content.length}});view.focus();}
function saveSettings(){api('settings',{theme:themePreference,mode,zoom}).catch(e=>toast('No se pudieron guardar las preferencias. '+e.message));}
function setMode(value){mode=value;document.body.dataset.mode=mode;$('#panes').dataset.mode=mode;for(const b of document.querySelectorAll('.segmented button')){b.classList.toggle('active',b.dataset.command===mode);b.setAttribute('aria-pressed',String(b.dataset.command===mode));}saveSettings();stats();if(mode==='edit')visual?.load(view?.state.doc.toString()||'');view?.requestMeasure();}
function setTheme(value,persist=true){if(persist)themePreference=value;theme=value;document.body.dataset.theme=theme;if(view)view.dispatch({effects:themeSlot.reconfigure(theme==='dark'?oneDark:[])});for(const d of documents.values())if(d.id!==active&&d.state)d.state=d.state.update({effects:themeSlot.reconfigure(theme==='dark'?oneDark:[])}).state;if(persist)saveSettings();visual?.refresh();schedule();}
function setZoom(value){zoom=Math.max(.8,Math.min(1.5,value));$('#zoom').textContent=Math.round(zoom*100)+'%';$('#editor').style.zoom=zoom;$('#preview').style.zoom=zoom;$('#visual-editor').style.zoom=zoom;saveSettings();view?.requestMeasure();}
async function closeDoc(id){if(id===active)await sync();if(!await api('close',id))return;documents.delete(id);if(id===active){active=null;if(documents.size)activate([...documents.keys()].at(-1));else accept(await api('new'));}else chrome();}
async function run(cmd){try{if(typeof cmd==='object'&&cmd.systemTheme){if(themePreference==='system')setTheme(cmd.systemTheme,false);return;}if(typeof cmd==='object'&&cmd.documentStates){for(const d of cmd.documentStates)mergeDocument(d);chrome();return;}if(typeof cmd==='object'&&cmd.openDoc){accept(cmd.openDoc);return;}if(['bold','italic','heading','link','image','list','task','quote','code','table','diagram'].includes(cmd)){format(cmd);return;}switch(cmd){case 'undo':undo(view);break;case 'redo':redo(view);break;case 'new':accept(await api('new'));setMode('edit');visual?.focus();break;case 'open':accept(await api('pickFile'));break;case 'folder':{const p=await api('pickFolder');if(p)await loadFolder(p);break;}case 'save':case 'saveAs':{const id=active;await sync(id);const saved=await api(cmd,id);if(saved){mergeDocument(saved);chrome();if(active===id)schedule();toast('Documento guardado');if(currentFolder)loadFolder(currentFolder).catch(()=>{});}break;}case 'close':await closeDoc(active);break;case 'theme':setTheme(theme==='dark'?'light':'dark');break;case 'systemTheme':themePreference='system';setTheme(await api('systemTheme'),false);saveSettings();break;case 'read':case 'edit':case 'split':setMode(cmd);break;case 'search':if(mode==='read')setMode('edit');if(mode==='edit'){$('#visual-search').hidden=false;$('#visual-find').focus();}else{openSearchPanel(view);view.focus();}break;case 'outline':$('#outline').hidden=!$('#outline').hidden;break;case 'focus':document.body.classList.toggle('focus');view.requestMeasure();break;case 'zoomIn':setZoom(zoom+.1);break;case 'zoomOut':setZoom(zoom-.1);break;case 'zoomReset':setZoom(1);break;case 'pdf':{const previous=mode,id=active;setMode('read');try{await render();await document.fonts.ready;await Promise.all([...$('#preview').querySelectorAll('img')].map(img=>img.decode().catch(()=>{})));if(id!==active)throw Error('Cambió el documento durante la preparación del PDF. Volvé a exportar.');await api('exportPdf',id);}finally{if(mode==='read')setMode(previous);}break;}}}catch(e){toast(e.message);}}
async function loadFolder(folder){const ticket=++folderGeneration;let listing;try{listing=await api('list',folder);}catch(e){if(ticket===folderGeneration)throw e;return;}if(ticket!==folderGeneration)return;currentFolder=folder;entries=listing;$('#path').value=folder;$('#path').title=folder;showFiles();for(const p of document.querySelectorAll('.place'))p.classList.toggle('active',p.dataset.path===folder);}
function showFiles(){const container=$('#files');container.replaceChildren();const filtered=entries.filter(e=>e.name.toLocaleLowerCase().includes($('#filter').value.toLocaleLowerCase()));for(const e of filtered){const b=textButton(e.name,e.directory?'folder':'file-text',()=>e.directory?loadFolder(e.path):api('open',e.path).then(accept));b.className='file'+(e.path===doc()?.path?' active':'');b.title=e.path;container.append(b);}if(!filtered.length){const message=document.createElement('div');message.className='empty';message.textContent=entries.length?'Sin coincidencias':'Esta carpeta no tiene documentos Markdown. Podés explorar sus subcarpetas o crear uno nuevo.';container.append(message);}icons();}
function showPlaces(p){const nav=$('#places');const section=(title,items,drive=false)=>{const label=document.createElement('div');label.className='section-label';label.textContent=title;nav.append(label);for(let index=0;index<items.length;index++){const item=items[index],b=textButton(item.name,drive?'hard-drive':(['monitor','download','file-text','images','music','video'][index]||'folder'),()=>loadFolder(item.path));b.className='place';b.dataset.path=item.path;b.title=item.path;nav.append(b);}};section('Acceso rápido',p.quick);if(p.extra.length){const details=document.createElement('details');const summary=document.createElement('summary');summary.textContent='Más accesos de Windows';details.append(summary);const original=nav;for(const item of p.extra){const b=textButton(item.name,'folder',()=>loadFolder(item.path));b.className='place';b.title=item.path;details.append(b);}nav.append(details);}nav.append(document.createElement('hr'));section('Este equipo',p.drives,true);icons();}
const md=new MarkdownIt({html:false,linkify:true,typographer:false}).use(tasks,{enabled:false}).use(frontMatterPlugin);
md.inline.ruler.before('escape','math',function(state,silent){if(state.src[state.pos]!=='$'||state.src[state.pos+1]==='$')return false;const end=state.src.indexOf('$',state.pos+1);if(end<0||state.src.slice(state.pos+1,end).includes('\n'))return false;if(!silent){const token=state.push('math_inline','math',0);token.content=state.src.slice(state.pos+1,end);}state.pos=end+1;return true;});
md.block.ruler.before('fence','math_block',function(state,start,end,silent){const first=state.src.slice(state.bMarks[start]+state.tShift[start],state.eMarks[start]);if(!first.startsWith('$$'))return false;let content=first.slice(2),next=start+1;if(content.endsWith('$$'))content=content.slice(0,-2);else{let found=false;for(;next<end;next++){const line=state.src.slice(state.bMarks[next],state.eMarks[next]);if(line.trim().endsWith('$$')){content+='\n'+line.slice(0,line.lastIndexOf('$$'));next++;found=true;break;}content+='\n'+line;}if(!found)return false;}if(!silent){const token=state.push('math_block','math',0);token.content=content;token.map=[start,next];}state.line=next;return true;});
const math=(tokens,index,display)=>{try{return katex.renderToString(tokens[index].content.trim(),{displayMode:display,throwOnError:true,trust:false,maxExpand:1000,maxSize:20});}catch{return '<span class="render-error">Fórmula no válida: '+md.utils.escapeHtml(tokens[index].content)+'</span>';}};
md.renderer.rules.math_inline=(t,i)=>math(t,i,false);md.renderer.rules.math_block=(t,i)=>math(t,i,true);
function schedule(){clearTimeout(renderTimer);generation++;renderTimer=setTimeout(()=>render().catch(e=>toast(e.message)),250);}
function render(){if(renderPromise){pending=true;return renderPromise;}renderPromise=(async()=>{do{pending=false;await renderOnce();}while(view&&doc()&&(pending||previewGeneration!==generation));})().finally(()=>{renderPromise=null;});return renderPromise;}
async function renderOnce(){if(!view||!doc())return;const ticket=generation,documentId=active,markdownText=view.state.doc.toString(),container=document.createElement('article');try{
container.innerHTML=DOMPurify.sanitize(md.render(markdownText),{ADD_TAGS:['math','annotation','semantics','mrow','mi','mo','mn','msup','mfrac'],FORBID_TAGS:['style','iframe','object','embed']});
for(const img of container.querySelectorAll('img')){const raw=img.getAttribute('src');img.removeAttribute('src');if(/^https?:/i.test(raw||'')){const note=document.createElement('span');note.className='media-error';note.textContent='Imagen remota · requiere conexión: '+(img.alt||raw);img.replaceWith(note);continue;}try{const source=await api('media',documentId,raw);img.src=source;img.addEventListener('error',()=>{const note=document.createElement('span');note.className='media-error';note.textContent='No se pudo cargar la imagen · '+img.alt;img.replaceWith(note);},{once:true});img.addEventListener('click',()=>expand(img));}catch{const note=document.createElement('span');note.className='media-error';note.textContent='Imagen local no disponible · '+img.alt;img.replaceWith(note);}}
for(const table of container.querySelectorAll('table')){const wrapper=document.createElement('div');wrapper.className='table-scroll';table.replaceWith(wrapper);wrapper.append(table);}
mermaid.initialize({startOnLoad:false,securityLevel:'strict',theme:theme==='dark'?'dark':'default',htmlLabels:false,maxTextSize:50000,maxEdges:500,suppressErrorRendering:true,flowchart:{htmlLabels:false,useMaxWidth:false},secure:['secure','securityLevel','startOnLoad','maxTextSize','maxEdges','htmlLabels']});let diagramCount=0,errors=0;
for(const code of container.querySelectorAll('pre>code')){if(!code.classList.contains('language-mermaid')){try{hljs.highlightElement(code);}catch{}continue;}const source=code.textContent,card=document.createElement('section');card.className='diagram-card';const tools=document.createElement('div');tools.className='graphic-tools';const label=document.createElement('span');label.textContent='Diagrama · Mermaid';tools.append(label);const content=document.createElement('div');content.className='diagram-content';const sourceCode=document.createElement('pre');sourceCode.className='diagram-code';sourceCode.textContent=source;tools.append(textButton('Código',null,()=>card.classList.toggle('show-code')));const enlarge=textButton('Ampliar',null,()=>{const svg=content.querySelector('svg');if(svg)expand(svg);});const save=textButton('SVG',null,()=>api('exportSvg',new XMLSerializer().serializeToString(content.querySelector('svg'))));tools.append(enlarge,save);card.append(tools,content,sourceCode);code.parentElement.replaceWith(card);try{if(source.length>50000||/%%\{\s*(init|config)/i.test(source)||/^\s*---\s*\n/.test(source))throw Error('Configuración embebida o tamaño no permitido.');const result=await mermaid.render('claro-'+ticket+'-'+diagramCount+'-'+crypto.randomUUID().replaceAll('-',''),source);content.innerHTML=DOMPurify.sanitize(result.svg,{USE_PROFILES:{svg:true,svgFilters:true},ADD_TAGS:['style']});const svg=content.querySelector('svg');if(!svg)throw Error('Gráfico vacío');svg.style.width=Math.max(180,svg.viewBox.baseVal.width)+'px';svg.style.maxWidth='none';diagramCount++;}catch(e){errors++;enlarge.disabled=true;save.disabled=true;const fallback=document.createElement('div');fallback.className='render-error';fallback.textContent='No se pudo dibujar el gráfico. '+String(e.message).split('\n')[0]+' Podés ver su código.';content.append(fallback);}}
let headingCount=0;const slugCounts=new Map();const outline=document.createDocumentFragment();for(const h of container.querySelectorAll('h1,h2,h3,h4,h5,h6')){const slug=h.textContent.toLowerCase().trim().replace(/[^\p{L}\p{N}\s_-]/gu,'').replace(/\s+/g,'-')||'heading';const count=slugCounts.get(slug)||0;slugCounts.set(slug,count+1);h.id=slug+(count?'-'+count:'');headingCount++;const b=textButton(h.textContent,null,()=>scrollHeading(h.id));b.style.paddingLeft=(Number(h.tagName[1])-1)*10+8+'px';outline.append(b);}
container.addEventListener('click',e=>{const link=e.target.closest('a');if(!link)return;e.preventDefault();const href=link.getAttribute('href');if(href?.startsWith('#')){scrollHeading(decodeURIComponent(href.slice(1)));return;}api('link',documentId,href).then(accept).catch(e=>toast(e.message));});
if(ticket===generation&&documentId===active){const scroller=$('#preview-scroll'),scroll=scroller.scrollTop;$('#preview').replaceChildren(...container.childNodes);$('#preview').onclick=container.onclick; // delegated links below survive node adoption
$('#preview').onclick=e=>{const a=e.target.closest('a');if(!a)return;e.preventDefault();const href=a.getAttribute('href');if(href.startsWith('#'))scrollHeading(decodeURIComponent(href.slice(1)));else api('link',active,href).then(accept).catch(e=>toast(e.message));};
$('#outline').replaceChildren(outline);scroller.scrollTop=scroll;const anchor=documents.get(documentId)?.pendingAnchor;if(anchor){scrollHeading(anchor);delete documents.get(documentId).pendingAnchor;}window.__claroRender={diagrams:diagramCount,errors,headings:headingCount};previewGeneration=ticket;window.__claroReady=true;}
}finally{}}
function scrollHeading(id){if(mode==='edit'){const heads=[...$('#preview').querySelectorAll('h1,h2,h3,h4,h5,h6')],index=heads.findIndex(h=>h.id===id),target=$('#visual-editor').querySelectorAll('h1,h2,h3,h4,h5,h6')[index],panel=$('#visual-scroll');if(target)panel.scrollTo({top:panel.scrollTop+target.getBoundingClientRect().top-panel.getBoundingClientRect().top-16,behavior:'smooth'});return;}if(!id){$('#preview-scroll').scrollTop=0;return;}const target=$('#preview').querySelector('#'+CSS.escape(id));if(target){const panel=$('#preview-scroll');panel.scrollTo({top:panel.scrollTop+target.getBoundingClientRect().top-panel.getBoundingClientRect().top-16,behavior:'smooth'});}}
function expand(element){$('#graphic-content').replaceChildren(element.cloneNode(true));$('#graphic-dialog').showModal();}
$('#formatbar').addEventListener('pointerdown',e=>{if(mode==='edit'&&e.target.closest('button'))e.preventDefault();});
$('#table-tools').addEventListener('pointerdown',e=>e.preventDefault());$('#table-tools').onclick=e=>{const action=e.target.dataset.table;if(action)visual.tableAction(action);};
$('#visual-search').addEventListener('click',e=>{const action=e.target.dataset.search;if(!action)return;if(action==='close'){$('#visual-search').hidden=true;visual.focus();return;}visual.search($('#visual-find').value,action==='previous'?-1:1,action==='replace'||action==='all'?$('#visual-replace').value:null,action==='all');});
$('#visual-find').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();visual.search(e.target.value,e.shiftKey?-1:1);}if(e.key==='Escape')$('#visual-search').hidden=true;};
document.addEventListener('click',e=>{const b=e.target.closest('[data-command]');if(b)run(b.dataset.command);});$('#dialog-close').onclick=()=>$('#graphic-dialog').close();$('#graphic-dialog').onclick=e=>{if(e.target===$('#graphic-dialog'))$('#graphic-dialog').close();};
$('#filter').oninput=showFiles;$('#path').onkeydown=e=>{if(e.key==='Enter')loadFolder(e.target.value).catch(e=>toast(e.message));};$('#refresh').onclick=()=>loadFolder(currentFolder).catch(e=>toast(e.message));$('#up').onclick=()=>{const parent=currentFolder.replace(/[\\/][^\\/]+[\\/]?$/,'');if(!parent&&currentFolder.startsWith('/')&&currentFolder!=='/')loadFolder('/').catch(e=>toast(e.message));if(parent)loadFolder(/^[A-Za-z]:$/.test(parent)?parent+'\\':parent).catch(e=>toast(e.message));};
$('#splitter').onpointerdown=e=>{const b=$('#panes').getBoundingClientRect();const move=e=>document.documentElement.style.setProperty('--editor-width',Math.min(75,Math.max(25,(e.clientX-b.left)/b.width*100))+'%');$('#splitter').setPointerCapture(e.pointerId);$('#splitter').onpointermove=move;$('#splitter').onpointerup=()=>{$('#splitter').onpointermove=null;view.requestMeasure();};};$('#splitter').onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){const width=parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--editor-width'))||50;document.documentElement.style.setProperty('--editor-width',Math.max(25,Math.min(75,width+(e.key==='ArrowRight'?5:-5)))+'%');view.requestMeasure();}};
window.claro.onCommand(run);
async function init(){const data=await api('bootstrap');if(data.platform==='darwin')for(const element of document.querySelectorAll('[title]'))element.title=element.title.replaceAll('Ctrl+','⌘');themePreference=data.settings.theme||'system';theme=data.theme;mode='edit';zoom=data.settings.zoom||1;document.body.dataset.theme=theme;view=new EditorView({state:makeState(''),parent:$('#editor')});visual=createVisual({element:$('#visual-editor'),md,getSource:()=>view.state.doc.toString(),getId:()=>active,onChange:applyVisual,run,api,ask:askVisual,toast,getTheme:()=>theme});showPlaces(data.places);for(const d of data.docs)documents.set(d.id,d);activate(data.docs[0].id);loadFolder(data.docs[0].path?data.docs[0].path.replace(/[\\/][^\\/]*$/,''):data.defaultFolder).catch(e=>toast(e.message));setMode(mode);setZoom(zoom);if(data.warnings?.length)toast(data.warnings.join(' '));else if(data.docs.some(d=>d.dirty))toast('Borradores recuperados: revisalos y guardalos cuando quieras.');initializing=false;window.__claroInitialized=true;await api('ready');if(data.auditing)window.__claroTest={api,run,view:()=>view,doc,accept,render,setTheme,setMode,loadFolder,documents,activate,visual};icons();}
init().catch(e=>toast(e.message));
