import {Editor,Extension,Node} from '@tiptap/core';
import StarterKit from '@tiptap/starter-kit';
import {Markdown} from '@tiptap/markdown';
import {TableKit} from '@tiptap/extension-table';
import TaskList from '@tiptap/extension-task-list';
import TaskItem from '@tiptap/extension-task-item';
import Image from '@tiptap/extension-image';
import {InlineMath,BlockMath} from '@tiptap/extension-mathematics';
import DOMPurify from 'dompurify';
import mermaid from 'mermaid';
import {frontMatter} from './frontmatter.js';

// Original text belongs to a top-level block. Unchanged blocks serialize verbatim.
const blockTypes=['paragraph','heading','blockquote','bulletList','orderedList','taskList','codeBlock','table','horizontalRule','blockMath','opaqueBlock'];
const identity=Extension.create({name:'sourceIdentity',addGlobalAttributes(){return [{types:blockTypes,attributes:{sourceKey:{default:null,rendered:false}}}];}});
const signature=node=>{const copy=JSON.parse(JSON.stringify(node));if(copy.attrs)delete copy.attrs.sourceKey;return JSON.stringify(copy);};
const safeLink=value=>{const normalized=String(value).trim().replace(/[\u0000-\u0020\u007f]/g,'');return /^(https?:|mailto:|#)/i.test(normalized)||(!/^[a-z][\w+.-]*:/i.test(normalized)&&!normalized.startsWith('//'));};

export function createVisual({element,md,getSource,getId,onChange,run,api,ask,toast,getTheme}){
 let originals=new Map(),prefix='',loaded='',loading=false,editor;
 const editMath=async(node,pos)=>{const id=getId(),result=await ask('Editar fórmula',node.attrs.latex,true);if(result!==null&&id===getId()&&!editor.isDestroyed)editor.commands.command(({tr})=>{tr.setNodeMarkup(pos,undefined,{...node.attrs,latex:result});return true;});};
 const inlineMath=InlineMath.extend({markdownTokenName:'lecatInlineMath',markdownTokenizer:{name:'lecatInlineMath',level:'inline',start:src=>src.indexOf('$'),tokenize:src=>{const match=/^\$([^$\n]+)\$/.exec(src);return match?{type:'lecatInlineMath',raw:match[0],latex:match[1]}:undefined;}},parseMarkdown:token=>({type:'inlineMath',attrs:{latex:token.latex}}),renderMarkdown:node=>'$'+node.attrs.latex+'$'}).configure({onClick:editMath,katexOptions:{trust:false,throwOnError:false,maxExpand:1000,maxSize:20}});
 const blockMath=BlockMath.extend({markdownTokenName:'lecatBlockMath',markdownTokenizer:{name:'lecatBlockMath',level:'block',start:src=>src.indexOf('$$'),tokenize:src=>{const match=/^\$\$([\s\S]*?)\$\$(?:\n|$)/.exec(src);return match?{type:'lecatBlockMath',raw:match[0],latex:match[1].trim()}:undefined;}},parseMarkdown:token=>({type:'blockMath',attrs:{latex:token.latex}}),renderMarkdown:node=>'$$\n'+node.attrs.latex+'\n$$'}).configure({onClick:editMath,katexOptions:{trust:false,throwOnError:false,maxExpand:1000,maxSize:20,displayMode:true}});
 const image=Image.extend({addNodeView(){return ({node})=>{const dom=document.createElement('span'),img=document.createElement('img');dom.className='visual-image';dom.contentEditable='false';img.alt=node.attrs.alt||'';dom.append(img);const id=getId();api('media',id,node.attrs.src).then(src=>{if(!editor.isDestroyed&&id===getId())img.src=src;}).catch(()=>{dom.textContent='Imagen local no disponible · '+(node.attrs.alt||node.attrs.src);});return {dom};};}}).configure({inline:true,allowBase64:false});
 const opaque=Node.create({name:'opaqueBlock',group:'block',atom:true,addAttributes(){return {raw:{default:''}};},parseHTML(){return [{tag:'div[data-opaque]'}];},renderHTML(){return ['div',{'data-opaque':'true'}];},renderMarkdown:node=>node.attrs.raw,
  addNodeView(){return ({node,getPos})=>{const dom=document.createElement('section'),body=document.createElement('div'),button=document.createElement('button');dom.className=/^\s*\[[^\]]+\]:/.test(node.attrs.raw)?'visual-special visual-definition':'visual-special';dom.contentEditable='false';body.innerHTML=DOMPurify.sanitize(md.render(node.attrs.raw));button.textContent=frontMatter(node.attrs.raw)?'Editar metadatos':/```mermaid|~~~mermaid/.test(node.attrs.raw)?'Editar diagrama':'Editar bloque';button.className='edit-special';button.onclick=async()=>{const id=getId(),result=await ask(button.textContent,node.attrs.raw,true);if(result!==null&&id===getId()&&!editor.isDestroyed){const pos=getPos();if(typeof pos==='number')editor.commands.command(({tr})=>{tr.setNodeMarkup(pos,undefined,{...node.attrs,raw:result});return true;});}};dom.append(body,button);
   for(const img of body.querySelectorAll('img')){const raw=img.getAttribute('src');img.removeAttribute('src');const id=getId();api('media',id,raw).then(src=>{if(!editor.isDestroyed&&id===getId())img.src=src;}).catch(()=>img.replaceWith(document.createTextNode('Imagen local no disponible')));}
   const code=body.querySelector('pre>code.language-mermaid');if(code){const source=code.textContent,box=document.createElement('div');box.className='diagram-content';code.parentElement.replaceWith(box);if(source.length>50000||/%%\{\s*(init|config)/i.test(source)||/^\s*---\s*\n/.test(source))box.textContent='Diagrama no válido. Usá Editar diagrama.';else{mermaid.initialize({startOnLoad:false,securityLevel:'strict',theme:getTheme()==='dark'?'dark':'default',htmlLabels:false,maxTextSize:50000,maxEdges:500,suppressErrorRendering:true,flowchart:{htmlLabels:false,useMaxWidth:true},secure:['secure','securityLevel','startOnLoad','maxTextSize','maxEdges','htmlLabels']});mermaid.render('visual-'+crypto.randomUUID().replaceAll('-',''),source).then(result=>{if(!editor.isDestroyed&&dom.isConnected)box.innerHTML=DOMPurify.sanitize(result.svg,{USE_PROFILES:{svg:true,svgFilters:true},ADD_TAGS:['style']});}).catch(()=>{box.textContent='No se pudo dibujar el diagrama. Usá Editar diagrama.';});}}
   return {dom,stopEvent:()=>true};};}
 });
 const shortcuts=Extension.create({name:'lecatShortcuts',addKeyboardShortcuts(){return {'Mod-s':()=>{run('save');return true;},'Mod-z':()=>{run('undo');return true;},'Mod-Shift-z':()=>{run('redo');return true;},'Mod-y':()=>{run('redo');return true;},'Mod-f':()=>{run('search');return true;}};}});
 editor=new Editor({element,extensions:[StarterKit.configure({undoRedo:false,underline:false,trailingNode:false,link:{openOnClick:false,autolink:false,isAllowedUri:safeLink}}),Markdown,TableKit.configure({table:{resizable:true}}),TaskList,TaskItem.configure({nested:true}),image,inlineMath,blockMath,opaque,identity,shortcuts],content:'',editorProps:{attributes:{class:'visual-document',role:'textbox','aria-label':'Documento visual editable','aria-multiline':'true'},handlePaste:(view,event)=>{const html=event.clipboardData?.getData('text/html');if(!html)return false;event.preventDefault();editor.commands.insertContent(DOMPurify.sanitize(html,{FORBID_TAGS:['img','iframe','object','embed','style','script'],FORBID_ATTR:['style','src','srcset']}));return true;}},onSelectionUpdate:()=>{const tools=document.querySelector('#table-tools');if(tools)tools.hidden=!editor.isActive('table');},onUpdate:()=>{if(!loading){const source=serialize();loaded=source;onChange(source);}}});
 function load(source,force=false){if(!force&&source===loaded)return;loading=true;originals=new Map();const tokens=md.parse(source,{}),starts=[];const offsets=[0];for(let i=0;i<source.length;i++)if(source[i]==='\n')offsets.push(i+1);for(const t of tokens)if(t.level===0&&t.map&&t.nesting!==-1)starts.push(offsets[t.map[0]]??source.length);const definitions=[];for(const match of source.matchAll(/^ {0,3}\[[^\]\n]+\]:[^\n]*(?:\n|$)/gm)){const line=source.slice(0,match.index).split('\n').length-1;if(!tokens.some(t=>['fence','code_block'].includes(t.type)&&t.map&&line>=t.map[0]&&line<t.map[1])){starts.push(match.index);definitions.push(match[0]);}}const front=frontMatter(source);const unique=[...new Set(starts)].filter(n=>!front||n===0||n>=front[0].length).sort((a,b)=>a-b);prefix=source.slice(0,unique[0]??source.length);const content=[];
  for(let i=0;i<unique.length;i++){const raw=source.slice(unique[i],unique[i+1]??source.length),key=crypto.randomUUID();let nodes;try{nodes=editor.markdown.parse(raw+'\n'+definitions.join('\n')).content?.filter(n=>!(n.type==='paragraph'&&!n.content?.length))||[];}catch{nodes=[];}let node=nodes.length===1?nodes[0]:{type:'opaqueBlock',attrs:{raw}};
   // Fences requiring a renderer and reference definitions remain lossless atoms.
   if(/^\s*(`{3,}|~{3,})mermaid\b/.test(raw)||/^\s*\[[^\]]+\]:/.test(raw)||/^\s*</.test(raw)||(front&&unique[i]===0))node={type:'opaqueBlock',attrs:{raw}};
   node.attrs={...node.attrs,sourceKey:key};originals.set(key,{raw,signature:signature(node)});content.push(node);
  }
  if(!content.length)content.push({type:'paragraph'});editor.commands.setContent({type:'doc',content},{emitUpdate:false});for(const node of editor.getJSON().content||[]){const original=originals.get(node.attrs?.sourceKey);if(original)original.signature=signature(node);}loaded=source;loading=false;
 }
 function serialize(){const nodes=editor.getJSON().content||[],used=new Set();return prefix+nodes.map((node,i)=>{const key=node.attrs?.sourceKey,original=originals.get(key);if(original&&!used.has(key)&&original.signature===signature(node)){used.add(key);return original.raw;}used.add(key);const text=editor.markdown.serialize({type:'doc',content:[node]});if(!text.trim())return '';const gap=original?.raw.match(/\n+$/)?.[0];return text.replace(/\n+$/,'')+(i<nodes.length-1?(gap&&gap.length>=2?gap:'\n\n'):(gap||''));}).join('');}
 async function format(kind){const chain=editor.chain().focus(),id=getId();const commands={bold:()=>chain.toggleBold().run(),italic:()=>chain.toggleItalic().run(),heading:()=>chain.toggleHeading({level:2}).run(),list:()=>chain.toggleBulletList().run(),task:()=>chain.toggleTaskList().run(),quote:()=>chain.toggleBlockquote().run(),code:()=>chain.toggleCodeBlock().run(),table:()=>chain.insertTable({rows:3,cols:2,withHeaderRow:true}).run()};if(commands[kind])return commands[kind]();if(kind==='link'){const value=await ask('Dirección del enlace',editor.getAttributes('link').href||'https://',false);if(value===null||id!==getId())return;if(!value.trim())return editor.chain().focus().unsetLink().run();if(!safeLink(value))throw Error('Usá un enlace web o una ruta de archivo.');editor.chain().focus().extendMarkRange('link').setLink({href:value}).run();}else if(kind==='image'){const value=await ask('Ruta de la imagen local','imagen.png',false);if(value&&id===getId())editor.chain().focus().setImage({src:value,alt:'Imagen'}).run();}else if(kind==='diagram'){const value=await ask('Nuevo diagrama Mermaid','flowchart LR\n  A[Idea] --> B[Resultado]',true);if(value&&id===getId())editor.chain().focus().insertContent({type:'opaqueBlock',attrs:{raw:'```mermaid\n'+value+'\n```'}}).run();}}
 function search(query,direction=1,replacement=null,all=false){if(!query)return 0;const matches=[];editor.state.doc.descendants((node,pos)=>{if(node.isText){let index=0;const text=node.text.toLocaleLowerCase(),needle=query.toLocaleLowerCase();while((index=text.indexOf(needle,index))>=0){matches.push({from:pos+index,to:pos+index+query.length});index+=query.length;}}});if(!matches.length){toast('Sin coincidencias.');return 0;}const selection=editor.state.selection;let match=direction>0?matches.find(m=>m.from>=selection.to):[...matches].reverse().find(m=>m.to<=selection.from);match ||= direction>0?matches[0]:matches.at(-1);if(replacement!==null){const selected=all?matches:[matches.find(m=>m.from===selection.from&&m.to===selection.to)||match];editor.commands.command(({tr})=>{for(const m of [...selected].reverse()){if(replacement)tr.insertText(replacement,m.from,m.to);else tr.delete(m.from,m.to);}return true;});}else editor.chain().focus().setTextSelection(match).scrollIntoView().run();return matches.length;}
 return {editor,load,serialize,format,search,focus:()=>editor.commands.focus(),refresh:()=>{const {from,to}=editor.state.selection,scroll=document.querySelector('#visual-scroll').scrollTop;load(getSource(),true);editor.commands.setTextSelection({from:Math.min(from,editor.state.doc.content.size),to:Math.min(to,editor.state.doc.content.size)});document.querySelector('#visual-scroll').scrollTop=scroll;},tableAction:action=>{const commands={row:'addRowAfter',column:'addColumnAfter',deleteRow:'deleteRow',deleteColumn:'deleteColumn',delete:'deleteTable'};if(commands[action])editor.chain().focus()[commands[action]]().run();},destroy:()=>editor.destroy()};
}
